---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: publish-to-cgw
  labels:
    app.kubernetes.io/version: "1.0.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to publish content to CGW (Content-Gateway)
  params:
    - name: cgwHostname
      type: string
      description: >
        The hostname of the content-gateway to publish the metadata to
      default: https://developers.redhat.com/content-gateway/rest/admin
    - name: cgwSecret
      type: string
      description: >
        The kubernetes secret to use to authenticate to content-gateway.
        It needs to contain two keys: username and token
      default: publish-to-cgw-secret
    - name: dataPath
      type: string
      description: >
        Path to the JSON string of the merged data to use in the data workspace.
    - name: contentDir
      type: string
      description: Path where the content to push is stored in the workspace
  results:
    - name: resultDataPath
      type: string
      description: |
        The relative path in the workspace to the stored json of result data of the task
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  steps:
    - name: run-push-cgw-metadata
      image: quay.io/konflux-ci/release-service-utils:afef3c73a8475f9db6534769e54e601cff1eb40b
      env:
        - name: CGW_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.cgwSecret)
              key: username
        - name: CGW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.cgwSecret)
              key: token
      script: |
        #!/usr/bin/env bash
        
        publish_to_cgw_wrapper \
            --cgw_host "$(params.cgwHostname)" \
            --data_file "$(workspaces.data.path)/$(params.dataPath)" \
            --content_dir "$(workspaces.data.path)/$(params.contentDir)" \
            --output_file "$(results.resultDataPath.path)"
